add services section complete
danielagenaro98/portfolio pull request #4
Opened 2021-08-25 22:59 UTC by danielagenaro98

Services section.

2021-08-30 19:54 UTC, frparodi requested changes

2021-08-30 19:54 UTC, frparodi commented on style.css
> +}
Dejá un espacio en blanco

2021-08-30 19:54 UTC, frparodi commented on index.html
> +    <div class="main-container-services">
Este div no es necesario. Si trasladas todos sus atributos, al div "services-section", y haces que el div "slides" sea hijo directo de "services-section", se te renderiza igual, y evitas ponerle una capa más a la cebolla que no hace la diferencia 😄 

Te quedaría algo asÍ:
```
<section id="services-section">
		<div class="slides">
			<div id="slide-1" class="slide">
                                <contenido del slide-1>
                         </div>
                 </div>
                 <los otros slides>
</section>
```

2021-08-30 20:39 UTC, danielagenaro98 commented on style.css
> +}
Listo

2021-08-30 20:42 UTC, danielagenaro98 commented on index.html
> +    <div class="main-container-services">
Sii, perfectooo

2021-08-31 00:03 UTC, frparodi approved these changes

2021-09-01 10:23 UTC, merged